// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ettrfzupsducalseyyzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0dHJmenVwc2R1Y2Fsc2V5eXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTExMzcsImV4cCI6MjA2MDk2NzEzN30.CZ1aC_4i10ifaNhSDzlU0V3XzV_bOzfz2Fvk3lctRDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);